# fly.toml app configuration file generated for steenberg-ecom-reviews on 2025-04-15T11:07:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'steenberg-ecom-reviews'
primary_region = 'yyz'

[build]

[env]
  HOST='https://steenberg-ecom-reviews.fly.dev'
  PORT=3000
  SCOPES='read_products,write_products'
  SHOPIFY_API_KEY='83e340b76fcab6c2eed330736f79857f'
  SHOPIFY_APP_URL='https://steenberg-ecom-reviews.fly.dev'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

